### ISSUE TITLE
Disabling the pruning pass if wanted

### ISSUE THREAD

**Issue by mehdidc** [jcrudy/py-earth#71]
I think  users should be able to disable the pruning pass if they want. The only way to do it currently is to use a big negative penalty, but one should find the value of the penalty for which never the basis functions get pruned. What about adding a enable_pruning parameter ?

**Comment by jcrudy** [comment]
@mehdidc Yeah, that sounds good to me.  There is currently an unprune method, but that has been made private and in any case it is good to be able to not do the pruning in the first place if you don't want to.  In general, I think more options around pruning are a good thing.

**Comment by jcrudy** [comment]
@mehdidc implemented this in commit bf263517c61567d5c4eded8aaa36588bc15fa952.
