### ISSUE TITLE
iteritems error on Python 3

### ISSUE THREAD

**Issue by mangecoeur** [jcrudy/py-earth#78]
Py-earth mostly seems to work fine in Python 3, with the exception of the `Model.__repr__()` function (line 788 in `earth.py`) which uses iteritems which doesn't work in py3. Since params should be short there shouldn't be any performance difference on py2 just using items:

```python
        for k, v in self.get_params().iteritems():
```

becomes

```python
        for k, v in self.get_params().items():
```

**Comment by jcrudy** [comment]
Thanks for reporting this.  It's fixed now, and py-earth should now be Python 3 compatible.  Please report back if you find otherwise.
