### ISSUE TITLE
issue about installation

### ISSUE THREAD

**Issue by CongB** [jcrudy/py-earth#91]
I'm using python 3.5.1 on windows 7 64bit...

> $ python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 88, in <module>
>     'long_description': open('README.md', 'r').read(),
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 3477: illegal multibyte sequence

**Comment by jcrudy** [comment]
Fixed by @mehdidc in PR #92.
